version: "3.8"

services:
  booking-service-db:
    image: postgres:15
    container_name: booking-service-db-container
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5433:5432"
    volumes:
      - booking-service-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-service:
    build:
      context: .
      dockerfile: ../booking-service/Dockerfile
    container_name: booking-service
    depends_on:
      - booking-service-db
    ports:      
      - "9090:9090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - dbConnectionString=Host=booking-service-db;Database=hotelio;Username=hotelio;Password=hotelio
      - hotelioMonolithUrl=http://monolith:8080
      - kafkaConnectionString=kafka:9092
    networks:
      - hotelio-net

  booking-history-db:
    image: postgres:15
    container_name: booking-history-db-container
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5434:5432"
    volumes:
      - booking-history-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-history-service:
    build:
      context: .
      dockerfile: ../booking-history-service/Dockerfile
    container_name: booking-history-service
    depends_on:
      - booking-history-db
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - kafkaConnectionString=kafka:9092
      - dbConnectionString=Host=booking-history-db;Database=hotelio;Username=hotelio;Password=hotelio
    networks:
      - hotelio-net

volumes:
  booking-history-db-data:
  booking-service-db-data:

networks:
  hotelio-net:
    external: true
